name: CI - Release

on:
  workflow_dispatch:
    inputs:
      commitOrTag:
        description: 'Commit or tag'
        required: false
        default: ''
  push:
    tags:
      - v*

jobs:
  release-image:
    permissions:
      id-token: write
      contents: write
    runs-on: docker
    env:
      GCP_REGISTRY_DOMAIN: asia-docker.pkg.dev
      GCP_REGISTRY: asia-docker.pkg.dev/${{ secrets.GCP_PRD_REGISTRY_PROJECT_ID }}/zilliqa-private
    steps:
    - name: 'Checkout scm ${{ inputs.commitOrTag }}'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.commitOrTag }}
    - name: Check if the commit or tag was passed manually
      id: set-tag
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag=$(git rev-parse HEAD | cut -c1-8)" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Check if the tag head is the same as master head
      id: check-latest
      if: github.event_name != 'workflow_dispatch'
      run: |
        if test $(git rev-parse origin/master) = $(git rev-parse HEAD); then
          echo "latest=true" >> $GITHUB_OUTPUT
        else
          echo "latest=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Docker build and push (GCP)
      uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v1
      with:
        file: docker/Dockerfile
        push: true
        tag: ${{ env.GCP_REGISTRY }}/scilla:${{ steps.set-tag.outputs.tag }}
        tag-latest: ${{ steps.check-latest.outputs.latest }}
        registry: ${{ env.GCP_REGISTRY_DOMAIN }}
        workload-identity-provider: "${{ secrets.GCP_PRD_GITHUB_WIF }}"
        service-account: "${{ secrets.GCP_PRD_GITHUB_SA_DOCKER_REGISTRY }}"
        cache-key: ${{ github.event.repository.name }}
    - name: Docker build and push (Dockerhub)
      uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v1
      with:
        file: docker/Dockerfile
        push: true
        tag: Zilliqa/scilla:${{ steps.set-tag.outputs.tag }}
        tag-latest: ${{ steps.check-latest.outputs.latest }}
        cache-key: ${{ github.event.repository.name }}
        registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
