scillaname: CI - Release

on:
  workflow_dispatch:
    inputs:
      commitOrTag:
        description: 'Commit or tag'
        required: false
        default: ''
  push:
    branches:
      - 'release/**'
    paths:
    - 'VERSION'
    tags:
      - v*

jobs:
  release-image:
    permissions:
      id-token: write
      contents: write
    runs-on: docker
    steps:
    - name: 'Checkout scm ${{ inputs.commitOrTag }}'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.commitOrTag }}
    - name: Docker build and push
      uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v1
      with:
        file: docker/Dockerfile
        push: true
        tag: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/scilla
        tag-length: 7
        tag-latest: ${{ github.ref == 'refs/heads/${{ github.event.repository.default_branch }}' }}
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ECR_DEPLOYER_ROLE }}
        oidc-role: ${{ secrets.OIDC_ROLE }}
        cache-key: ${{ github.event.repository.name }}
    - name: Docker build and push (Dockerhub)
      uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v1
      with:
        file: .github/test/Dockerfile
        push: true
        tag: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/scilla:dockerhub
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        cache-key: ${{ github.event.repository.name }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecr-read-write
        oidc-role: ${{ secrets.OIDC_ROLE }}
        registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
